// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnuB37JUfYVo5BWO6uxA14yC7JVbfqfcI',
    appId: '1:301587046614:web:ec8da2253cf4a86e296977',
    messagingSenderId: '301587046614',
    projectId: 'consultant-d76cd',
    authDomain: 'consultant-d76cd.firebaseapp.com',
    storageBucket: 'consultant-d76cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH5OjLLrPyS04s_QFrAuASsKxK8CyjEmo',
    appId: '1:301587046614:android:15c52a9fb9565d4c296977',
    messagingSenderId: '301587046614',
    projectId: 'consultant-d76cd',
    storageBucket: 'consultant-d76cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDocEyxxLy8QdarnjjYtIOtB141LrDlpFc',
    appId: '1:301587046614:ios:409182490d49a50d296977',
    messagingSenderId: '301587046614',
    projectId: 'consultant-d76cd',
    storageBucket: 'consultant-d76cd.appspot.com',
    iosClientId: '301587046614-k5j8il914nt4qvsoqt12mui16et38ns6.apps.googleusercontent.com',
    iosBundleId: 'com.example.consultant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDocEyxxLy8QdarnjjYtIOtB141LrDlpFc',
    appId: '1:301587046614:ios:409182490d49a50d296977',
    messagingSenderId: '301587046614',
    projectId: 'consultant-d76cd',
    storageBucket: 'consultant-d76cd.appspot.com',
    iosClientId: '301587046614-k5j8il914nt4qvsoqt12mui16et38ns6.apps.googleusercontent.com',
    iosBundleId: 'com.example.consultant',
  );
}
